### ISSUE TITLE
no images for WIF projects

### ISSUE THREAD

**Issue by moedn** [ahane/LOSH-krawler#6]
The Krawler doesn't seem to get image data from WIF. Here are two examples:

- Zoomografo
  - [frontend](https://zen-stonebraker-a93ddf.netlify.app/detail/Q451)
  - [wikibase](https://losh.ose-germany.de/index.php?title=Item:Q451)
  - [WIF](https://wikifactory.com/@hackability/zoomografo)
- Flexo
  - [frontend](https://zen-stonebraker-a93ddf.netlify.app/detail/Q453)
  - [wikibase](https://losh.ose-germany.de/index.php?title=Item:Q453)
  - [WIF](https://wikifactory.com/@pachek/flexo)

**Comment by ahane** [comment]
fixed in wf
